version: '3.3'
name: data-farm

services:
  app:
    container_name: data-farm-app
    build:
      context: .
      dockerfile: ./docker/Dockerfile.app
    tty: true
    volumes:
      - ./:/usr/src/app
    restart: always
